openapi: 3.0.3
info:
  title: Authentication API
  description: API for user authentication and JWT issuance
  version: 1.0.0

servers:
  - url: https://api.example.com

paths:
  /auth/login:
    post:
      summary: User login
      description: Authenticates user credentials and returns a JWT access token.
      operationId: loginUser
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            example:
              username: john.doe@example.com
              password: P@ssw0rd123
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
              example:
                accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                tokenType: Bearer
                expiresIn: 900
        '401':
          description: Invalid username or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: UNAUTHORIZED
                message: Invalid credentials
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/token/validate:
    post:
      summary: Validate JWT token
      description: Validates a JWT access token from the Authorization header.
      operationId: validateToken
      tags:
        - Authentication
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer access token
          schema:
            type: string
            example: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...
      responses:
        '200':
          description: Token validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenValidationResponse'
              example:
                valid: true
        '400':
          description: Missing or malformed Authorization header
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          format: email
          description: User email or username
        password:
          type: string
          format: password
          description: User password

    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT access token
        tokenType:
          type: string
          example: Bearer
        expiresIn:
          type: integer
          description: Token expiry time in seconds

    TokenValidationResponse:
      type: object
      properties:
        valid:
          type: boolean
          description: Indicates whether the token is valid

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
