openapi: 3.0.3
info:
  title: Payment API
  description: API for managing payment transactions with support for multiple payment methods and statuses
  version: 1.0.0
  contact:
    name: Payment API Support
    email: support@payments.com

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://api.payments.com/api/v1
    description: Production server

tags:
  - name: Payments
    description: Payment transaction operations

paths:
  /payments/{id}:
    get:
      tags:
        - Payments
      summary: Get payment by ID
      description: Retrieves a payment transaction by its unique identifier
      operationId: getPaymentById
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the payment
          schema:
            type: integer
            format: int64
            example: 12345
      responses:
        '200':
          description: Payment found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                timestamp: "2024-12-20T10:30:00Z"
                status: 404
                error: "Not Found"
                message: "Payment with id 12345 not found"
                path: "/api/v1/payments/12345"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /payments:
    post:
      tags:
        - Payments
      summary: Create a new payment
      description: Creates a new payment transaction
      operationId: makePayment
      requestBody:
        required: true
        description: Payment details to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '201':
          description: Payment created successfully
          headers:
            Location:
              description: URI of the created payment
              schema:
                type: string
                example: "/api/payments/12345"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '400':
          description: Invalid payment data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                timestamp: "2024-12-20T10:30:00Z"
                status: 400
                error: "Bad Request"
                message: "Invalid payment details provided"
                path: "/api/v1/payments"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Payment:
      type: object
      required:
        - amount
        - currency
        - status
        - paymentMethod
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier of the payment
          example: 12345
        amount:
          type: number
          format: decimal
          description: Payment amount
          minimum: 0.01
          example: 999.99
        currency:
          type: string
          description: Currency code (ISO 4217)
          pattern: '^[A-Z]{3}$'
          example: USD
        status:
          $ref: '#/components/schemas/PaymentStatus'
        paymentMethod:
          $ref: '#/components/schemas/PaymentMethod'
        createdAt:
          type: string
          format: date-time
          description: Timestamp when payment was created
          example: "2024-12-20T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when payment was last updated
          example: "2024-12-20T10:35:00Z"

    PaymentRequest:
      type: object
      required:
        - amount
        - currency
        - paymentMethod
      properties:
        amount:
          type: number
          format: decimal
          description: Payment amount
          minimum: 0.01
          example: 999.99
        currency:
          type: string
          description: Currency code (ISO 4217)
          pattern: '^[A-Z]{3}$'
          example: USD
        paymentMethod:
          $ref: '#/components/schemas/PaymentMethod'

    PaymentStatus:
      type: string
      description: Current status of the payment transaction
      enum:
        - PENDING
        - PROCESSING
        - COMPLETED
        - FAILED
        - REFUNDED
        - CANCELLED
      example: COMPLETED

    PaymentMethod:
      type: string
      description: Payment method used for the transaction
      enum:
        - CREDIT_CARD
        - DEBIT_CARD
        - UPI
        - NET_BANKING
        - WALLET
        - CASH_ON_DELIVERY
      example: CREDIT_CARD

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the error occurred
          example: "2024-12-20T10:30:00Z"
        status:
          type: integer
          description: HTTP status code
          example: 404
        error:
          type: string
          description: Error type
          example: "Not Found"
        message:
          type: string
          description: Detailed error message
          example: "Payment with id 12345 not found"
        path:
          type: string
          description: API path where the error occurred
          example: "/api/v1/payments/12345"